<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersWorkersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Desactivamos auto-incremento temporalmente
        DB::statement('ALTER TABLE workers AUTO_INCREMENT = 10;');

        $workers = [
            // Personal Docente de Educación Primaria - worker_id desde 10
            ['id' => 10, 'user_id' => 10, 'first_name' => 'Yudyth Del Carmen', 'last_name' => 'Escobar Ramirez', 'identification' => '12281501', 'hire_date' => '2006-09-01', 'base_salary' => 500.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'yudyth.escobar@uefrayluisamigosf.com', 'phone' => '584145459268', 'is_active' => true],
            ['id' => 11, 'user_id' => 11, 'first_name' => 'Maribel', 'last_name' => 'Garcia Sierra', 'identification' => '7580377', 'hire_date' => '2008-10-01', 'base_salary' => 500.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'maribel.garcia@uefrayluisamigosf.com', 'phone' => '584166436750', 'is_active' => true],
            ['id' => 12, 'user_id' => 12, 'first_name' => 'Yvonne Leticia', 'last_name' => 'Puerta Yanez', 'identification' => '7913801', 'hire_date' => '2018-10-08', 'base_salary' => 455.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'yvonne.puertas@uefrayluisamigosf.com', 'phone' => '584121562163', 'is_active' => true],
            ['id' => 13, 'user_id' => 13, 'first_name' => 'Agne Cecilia', 'last_name' => 'Bazan Bermudez', 'identification' => '4123862', 'hire_date' => '2019-05-02', 'base_salary' => 455.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'agnes.bazan@uefrayluisamigosf.com', 'phone' => '584151515000', 'is_active' => true],
            ['id' => 14, 'user_id' => 14, 'first_name' => 'Helencleomar', 'last_name' => 'Dos Santos Carrera', 'identification' => '19063141', 'hire_date' => '2020-09-16', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'helencleomar.dossantos@uefrayluisamigosf.com', 'phone' => '584124160034', 'is_active' => true],
            ['id' => 15, 'user_id' => 15, 'first_name' => 'Cecilia Rosa', 'last_name' => 'Colmenarez Montañez', 'identification' => '4476763', 'hire_date' => '2022-09-12', 'base_salary' => 165.00, 'contract_type' => 'FHC', 'payment_method' => 'bank_transfer', 'email' => 'cecilia.colmenarez@uefrayluisamigosf.com', 'phone' => '584166010532', 'is_active' => true],
            ['id' => 16, 'user_id' => 16, 'first_name' => 'Ada Griselda', 'last_name' => 'Crespo Leon', 'identification' => '16955322', 'hire_date' => '2023-01-16', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'ada.griselda.crespo.leon@uefrayluisamigosf.com', 'phone' => '584145166721', 'is_active' => true],
            ['id' => 17, 'user_id' => 17, 'first_name' => 'Vanessa', 'last_name' => 'Sanchez', 'identification' => '17641770', 'hire_date' => '2023-09-16', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'VANESSA.DEL.CARMEN.SANCHEZ.PARRA@uefrayluisamigosf.com', 'phone' => '584125192402', 'is_active' => true],
            ['id' => 18, 'user_id' => 18, 'first_name' => 'Rafaela', 'last_name' => 'Dominguez', 'identification' => '7583743', 'hire_date' => '2023-09-11', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'mireya.dominguez@uefrayluisamigosf.com', 'phone' => '584121552446', 'is_active' => true],
            ['id' => 19, 'user_id' => 19, 'first_name' => 'Ibranny', 'last_name' => 'Oropeza', 'identification' => '19062348', 'hire_date' => '2023-09-11', 'base_salary' => 440.00, 'contract_type' => 'Docente Robotica', 'payment_method' => 'bank_transfer', 'email' => 'ibranny.oropeza@uefrayluisamigosf.com', 'phone' => '584129161680', 'is_active' => true],
            ['id' => 20, 'user_id' => 20, 'first_name' => 'Maria', 'last_name' => "D'Lima", 'identification' => '20464137', 'hire_date' => '2023-09-11', 'base_salary' => 440.00, 'contract_type' => 'Docente Robotica', 'payment_method' => 'bank_transfer', 'email' => 'maria.dlima@uefrayluisamigosf.com', 'phone' => '584166507698', 'is_active' => true],
            ['id' => 21, 'user_id' => 21, 'first_name' => 'Nilinska Yanneth', 'last_name' => 'Alvarado Urriche', 'identification' => '15108396', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Docente de Inicial', 'payment_method' => 'bank_transfer', 'email' => 'nilinska.alvarado@uefrayluisamigosf.com', 'phone' => '584120586507', 'is_active' => true],
            ['id' => 22, 'user_id' => 22, 'first_name' => 'Yendri Carolina', 'last_name' => 'Escalona Chirino', 'identification' => '17679039', 'hire_date' => '2024-09-19', 'base_salary' => 440.00, 'contract_type' => 'Docente de Inicial', 'payment_method' => 'bank_transfer', 'email' => 'yendri.escalona@uefrayluisamigosf.com', 'phone' => '584121695270', 'is_active' => true],
            ['id' => 23, 'user_id' => 23, 'first_name' => 'Kellimar', 'last_name' => 'Castillo Rodriguez', 'identification' => '16260832', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Docente de Inicial', 'payment_method' => 'bank_transfer', 'email' => 'kellimar.rodriguez@uefrayluisamigosf.com', 'phone' => '584542333990', 'is_active' => true],
            ['id' => 24, 'user_id' => 24, 'first_name' => 'Heira Mariel', 'last_name' => 'Sequera Lovera', 'identification' => '12286317', 'hire_date' => '2024-09-13', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'heira.sequera@uefrayluisamigosf.com', 'phone' => '584000000000', 'is_active' => true],
            ['id' => 25, 'user_id' => 25, 'first_name' => 'Scarleth Anais', 'last_name' => 'Tovar Alejos', 'identification' => '17255816', 'hire_date' => '2024-09-13', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'scarlet.tovar@uefrayluisamigosf.com', 'phone' => '584125192402', 'is_active' => true],
            ['id' => 26, 'user_id' => 26, 'first_name' => 'Maria Gabriela', 'last_name' => 'Perez Salas', 'identification' => '13230943', 'hire_date' => '2024-09-09', 'base_salary' => 165.00, 'contract_type' => 'FHC', 'payment_method' => 'bank_transfer', 'email' => 'maria.perez.salas@uefrayluisamigosf.com', 'phone' => '584000000000', 'is_active' => true],
            ['id' => 27, 'user_id' => 27, 'first_name' => 'Anne Carolina', 'last_name' => 'Van Denker', 'identification' => '10368288', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Tiempo Completo', 'payment_method' => 'bank_transfer', 'email' => 'anne.vandenker@uefrayluisamigosf.com', 'phone' => '584262518156', 'is_active' => true],
            ['id' => 28, 'user_id' => 28, 'first_name' => 'Anna Yulianny', 'last_name' => 'Bazan Guevara', 'identification' => '27699587', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Docente de Musica', 'payment_method' => 'bank_transfer', 'email' => 'anna.bazan@uefrayluisamigosf.com', 'phone' => '584124759687', 'is_active' => true],

            // Personal Docente de Educación Media General - worker_id 29+
            ['id' => 29, 'user_id' => 29, 'first_name' => 'Aura Josefina', 'last_name' => 'Mendoza Figueira', 'identification' => '5465942', 'hire_date' => '2016-11-01', 'base_salary' => 307.13, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'aura.mendoza@uefrayluisamigosf.com', 'phone' => '584145250000', 'is_active' => true],
            ['id' => 30, 'user_id' => 30, 'first_name' => 'Isabel Josefina', 'last_name' => 'Mora De Tampoo', 'identification' => '4482280', 'hire_date' => '2018-04-02', 'base_salary' => 216.13, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'isabel.mora@uefrayluisamigosf.com', 'phone' => '584168600000', 'is_active' => true],
            ['id' => 31, 'user_id' => 31, 'first_name' => 'Carmin Andrieina', 'last_name' => 'Cortez Alejos', 'identification' => '20922623', 'hire_date' => '2019-01-08', 'base_salary' => 489.13, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'carmin.cortez@uefrayluisamigosf.com', 'phone' => '584245450754', 'is_active' => true],
            ['id' => 32, 'user_id' => 32, 'first_name' => 'Ysabel Mirelli', 'last_name' => 'Camacho Moreno', 'identification' => '12728521', 'hire_date' => '2019-04-05', 'base_salary' => 443.63, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'ysabel.camacho@uefrayluisamigosf.com', 'phone' => '584542315243', 'is_active' => true],
            ['id' => 33, 'user_id' => 33, 'first_name' => 'Milagros Del Carmen', 'last_name' => 'Rios Deviez', 'identification' => '11274339', 'hire_date' => '2022-09-16', 'base_salary' => 500.50, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'milagros.rios@uefrayluisamigosf.com', 'phone' => '584120588539', 'is_active' => true],
            ['id' => 34, 'user_id' => 34, 'first_name' => 'Victor Hugo', 'last_name' => 'Maldonado Gimenez', 'identification' => '12280253', 'hire_date' => '2022-09-16', 'base_salary' => 546.00, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'victor.maldonado@uefrayluisamigosf.com', 'phone' => '584145725790', 'is_active' => true],
            ['id' => 35, 'user_id' => 35, 'first_name' => 'Daniel', 'last_name' => 'Marchena Portilla', 'identification' => '10343362', 'hire_date' => '2022-09-16', 'base_salary' => 398.13, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'daniel.marchena@uefrayluisamigosf.com', 'phone' => '584245316730', 'is_active' => true],
            ['id' => 36, 'user_id' => 36, 'first_name' => 'Miguel Angel', 'last_name' => 'Montilva Hernandez', 'identification' => '8513337', 'hire_date' => '2022-03-14', 'base_salary' => 409.50, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'miguel.montilva@uefrayluisamigosf.com', 'phone' => '584129979954', 'is_active' => true],
            ['id' => 37, 'user_id' => 37, 'first_name' => 'Enrique', 'last_name' => 'Segovia', 'identification' => '9162912', 'hire_date' => '2023-09-01', 'base_salary' => 216.13, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'enrique.segovia@uefrayluisamigosf.com', 'phone' => '584122912430', 'is_active' => true],
            ['id' => 38, 'user_id' => 38, 'first_name' => 'Moises', 'last_name' => 'Ordoñez', 'identification' => '17611704', 'hire_date' => '2023-09-11', 'base_salary' => 500.50, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'moises.ordonez@uefrayluisamigosf.com', 'phone' => '584125453681', 'is_active' => true],
            ['id' => 39, 'user_id' => 39, 'first_name' => 'Tania', 'last_name' => 'Alvarez', 'identification' => '10365854', 'hire_date' => '2023-09-16', 'base_salary' => 318.50, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'tania.alvarez@uefrayluisamigosf.com', 'phone' => '584121527370', 'is_active' => true],
            ['id' => 40, 'user_id' => 40, 'first_name' => 'Jose Gabriel', 'last_name' => 'Torres Villalobos', 'identification' => '28121558', 'hire_date' => '2020-04-01', 'base_salary' => 455.00, 'contract_type' => 'Innovación Tecnológica / Robótica', 'payment_method' => 'bank_transfer', 'email' => 'jose.torres.villalobos@uefrayluisamigosf.com', 'phone' => '584263047766', 'is_active' => true],

            // Docentes de Inglés - worker_id 41+
            ['id' => 41, 'user_id' => 41, 'first_name' => 'Roxangel', 'last_name' => 'Rodriguez', 'identification' => '11647051', 'hire_date' => '2023-09-16', 'base_salary' => 540.00, 'contract_type' => 'Jefe Proyecto Ingles', 'payment_method' => 'bank_transfer', 'email' => 'roxangel.rodriguez@uefrayluisamigosf.com', 'phone' => '584160487540', 'is_active' => true],
            ['id' => 42, 'user_id' => 42, 'first_name' => 'Narda Maria', 'last_name' => 'Matos Contreras', 'identification' => '6823506', 'hire_date' => '2018-11-08', 'base_salary' => 495.00, 'contract_type' => 'Docente Ingles', 'payment_method' => 'bank_transfer', 'email' => 'narda.matos@uefrayluisamigosf.com', 'phone' => '584261675303', 'is_active' => true],
            ['id' => 43, 'user_id' => 43, 'first_name' => 'Alejandra Barbara', 'last_name' => 'Piñero Villegas', 'identification' => '30562726', 'hire_date' => '2024-09-10', 'base_salary' => 473.00, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'alejandra.pinero@uefrayluisamigosf.com', 'phone' => '584166537183', 'is_active' => true],
            ['id' => 44, 'user_id' => 44, 'first_name' => 'Roberto Andres', 'last_name' => 'Sanchez Guevara', 'identification' => '16110260', 'hire_date' => '2024-09-10', 'base_salary' => 429.00, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'roberto.sanchez@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 45, 'user_id' => 45, 'first_name' => 'Gabriela Alejandra', 'last_name' => 'Ordóñez Novello', 'identification' => '30868096', 'hire_date' => '2024-09-10', 'base_salary' => 385.00, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'gabriela.ordonez@uefrayluisamigosf.com', 'phone' => '584145714425', 'is_active' => true],
            ['id' => 46, 'user_id' => 46, 'first_name' => 'Jose Delfin', 'last_name' => 'Muñoz Galup', 'identification' => '12083718', 'hire_date' => '2024-09-10', 'base_salary' => 429.00, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'jose.munoz@uefrayluisamigosf.com', 'phone' => '584125068420', 'is_active' => true],
            ['id' => 47, 'user_id' => 47, 'first_name' => 'Roderyt Javier', 'last_name' => 'Berriz Dorante', 'identification' => '18302157', 'hire_date' => '2024-09-10', 'base_salary' => 539.00, 'contract_type' => 'Por Horas', 'payment_method' => 'bank_transfer', 'email' => 'roderyt.berriz@uefrayluisamigosf.com', 'phone' => '584254234306', 'is_active' => true],

            // Dirección y Coordinaciones Académicas - worker_id 48+
            ['id' => 48, 'user_id' => 48, 'first_name' => 'Escarleth', 'last_name' => 'Lopez De Antolini', 'identification' => '7593218', 'hire_date' => '2022-10-01', 'base_salary' => 600.00, 'contract_type' => 'Director Academico', 'payment_method' => 'bank_transfer', 'email' => 'escarleth.lopez@uefrayluisamigosf.com', 'phone' => '584127611380', 'is_active' => true],
            ['id' => 49, 'user_id' => 49, 'first_name' => 'Rinna Gabriela', 'last_name' => 'Chacon Colmenarez', 'identification' => '12936044', 'hire_date' => '2022-09-05', 'base_salary' => 600.00, 'contract_type' => 'Sub Director Academico', 'payment_method' => 'bank_transfer', 'email' => 'rinna.chacon@uefrayluisamigosf.com', 'phone' => '584123308981', 'is_active' => true],
            ['id' => 50, 'user_id' => 50, 'first_name' => 'Lidoska Beatriz', 'last_name' => 'Veliz Dudamell', 'identification' => '7914556', 'hire_date' => '2018-02-01', 'base_salary' => 540.00, 'contract_type' => 'Coordinador Registros y Estudiantes', 'payment_method' => 'bank_transfer', 'email' => 'lidoska.veliz@uefrayluisamigosf.com', 'phone' => '584120523156', 'is_active' => true],
            ['id' => 51, 'user_id' => 51, 'first_name' => 'Harold Alexander', 'last_name' => 'Parra Figueroa', 'identification' => '11276458', 'hire_date' => '2022-09-16', 'base_salary' => 455.00, 'contract_type' => 'Coordinador de Evaluación', 'payment_method' => 'bank_transfer', 'email' => 'harold.parra@uefrayluisamigosf.com', 'phone' => '584265543804', 'is_active' => true],
            ['id' => 52, 'user_id' => 52, 'first_name' => 'Idalmis Mercedes', 'last_name' => 'Rubinettti Marquez', 'identification' => '6526416', 'hire_date' => '2022-03-11', 'base_salary' => 540.00, 'contract_type' => 'Coordinador Primera Etapa', 'payment_method' => 'bank_transfer', 'email' => 'labrujitair@gmail.com', 'phone' => '584000000000', 'is_active' => true],
            ['id' => 53, 'user_id' => 53, 'first_name' => 'Elizabeth Del Rosario', 'last_name' => 'Ortaz De Raban', 'identification' => '4353047', 'hire_date' => '2006-01-09', 'base_salary' => 540.00, 'contract_type' => 'Coordinador Segunda Etapa', 'payment_method' => 'bank_transfer', 'email' => 'elizabeth.ortaz@uefrayluisamigosf.com', 'phone' => '584121564921', 'is_active' => true],
            ['id' => 54, 'user_id' => 54, 'first_name' => 'Alejandra', 'last_name' => 'Betancourt Valero', 'identification' => '23575267', 'hire_date' => '2022-09-12', 'base_salary' => 540.00, 'contract_type' => 'Coordinador Bienestar Estudiantil', 'payment_method' => 'bank_transfer', 'email' => 'alejandra.betancourt@uefrayluisamigosf.com', 'phone' => '584120508848', 'is_active' => true],

            // Bienestar Estudiantil - worker_id 55+
            ['id' => 55, 'user_id' => 55, 'first_name' => 'Richard', 'last_name' => 'Salas', 'identification' => '15483521', 'hire_date' => '2023-09-16', 'base_salary' => 440.00, 'contract_type' => 'Docente Deporte', 'payment_method' => 'bank_transfer', 'email' => 'richard.salas@uefrayluisamigosf.com', 'phone' => '584120533510', 'is_active' => true],
            ['id' => 56, 'user_id' => 56, 'first_name' => 'Emilia', 'last_name' => 'Guedez', 'identification' => '7582484', 'hire_date' => '2023-09-11', 'base_salary' => 440.00, 'contract_type' => 'Aula Integrada', 'payment_method' => 'bank_transfer', 'email' => 'guedez.nadal@uefrayluisamigosf.com', 'phone' => '584125108520', 'is_active' => true],
            ['id' => 57, 'user_id' => 57, 'first_name' => 'Rosa Elena', 'last_name' => 'Marquez Campos', 'identification' => '8516544', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Psicopedagogo', 'payment_method' => 'bank_transfer', 'email' => 'rosa.marquez@uefrayluisamigosf.com', 'phone' => '584166537183', 'is_active' => true],
            ['id' => 58, 'user_id' => 58, 'first_name' => 'Maryangel Mercedes', 'last_name' => 'Garrido Lozada', 'identification' => '23573152', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Psicologo', 'payment_method' => 'bank_transfer', 'email' => 'maryangel.garrido@uefrayluisamigosf.com', 'phone' => '584145714425', 'is_active' => true],
            ['id' => 59, 'user_id' => 59, 'first_name' => 'Maria', 'last_name' => 'Silva Tesvari', 'identification' => '12281064', 'hire_date' => '2024-09-09', 'base_salary' => 440.00, 'contract_type' => 'Orientador', 'payment_method' => 'bank_transfer', 'email' => 'maria.silva@uefrayluisamigosf.com', 'phone' => '584145714425', 'is_active' => true],
            ['id' => 60, 'user_id' => 60, 'first_name' => 'Lenin Alberto', 'last_name' => 'Fernandez Yovera', 'identification' => '17700109', 'hire_date' => '2020-01-29', 'base_salary' => 455.00, 'contract_type' => 'Docente Por Hora', 'payment_method' => 'bank_transfer', 'email' => 'lenin.fernandez@uefrayluisamigosf.com', 'phone' => '584143547886', 'is_active' => true],

            // Personal de Mantenimiento - worker_id 61+
            ['id' => 61, 'user_id' => 61, 'first_name' => 'Australida Josefina', 'last_name' => 'Figuerola De Blanco', 'identification' => '7281411', 'hire_date' => '1987-09-01', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'australida.figuerola@uefrayluisamigosf.com', 'phone' => '584145459268', 'is_active' => true],
            ['id' => 62, 'user_id' => 62, 'first_name' => 'Temistocles', 'last_name' => 'Rodriguez Gamez', 'identification' => '3707596', 'hire_date' => '1979-01-02', 'base_salary' => 160.00, 'contract_type' => 'Aseador', 'payment_method' => 'bank_transfer', 'email' => 'temistocles.rodriguez@uefrayluisamigosf.com', 'phone' => '584166436750', 'is_active' => true],
            ['id' => 63, 'user_id' => 63, 'first_name' => 'Luis Felipe', 'last_name' => 'Anzola', 'identification' => '4123780', 'hire_date' => '1997-01-10', 'base_salary' => 160.00, 'contract_type' => 'Aseador', 'payment_method' => 'bank_transfer', 'email' => 'luis.anzola@uefrayluisamigosf.com', 'phone' => '584166010532', 'is_active' => true],
            ['id' => 64, 'user_id' => 64, 'first_name' => 'Nancy Mariela', 'last_name' => 'Arenas', 'identification' => '7554731', 'hire_date' => '2000-02-01', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'nancy.arenas@uefrayluisamigosf.com', 'phone' => '584245966956', 'is_active' => true],
            ['id' => 65, 'user_id' => 65, 'first_name' => 'Yamileth Yasmin', 'last_name' => 'Parra Guerra', 'identification' => '13313250', 'hire_date' => '2018-05-02', 'base_salary' => 160.00, 'contract_type' => 'Servicios Privados', 'payment_method' => 'bank_transfer', 'email' => 'yamileth.parra@uefrayluisamigosf.com', 'phone' => '584166537183', 'is_active' => true],
            ['id' => 66, 'user_id' => 66, 'first_name' => 'Elizabeth', 'last_name' => 'Montero Camacho', 'identification' => '15767557', 'hire_date' => '2018-10-01', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'elizabeth.montero@uefrayluisamigosf.com', 'phone' => '584125068420', 'is_active' => true],
            ['id' => 67, 'user_id' => 67, 'first_name' => 'Coromoto', 'last_name' => 'Marchena Zugeith', 'identification' => '14608115', 'hire_date' => '2019-03-21', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'coromoto.marchena@uefrayluisamigosf.com', 'phone' => '584542343064', 'is_active' => true],
            ['id' => 68, 'user_id' => 68, 'first_name' => 'Vicente Elias', 'last_name' => 'Hernandez Coronado', 'identification' => '5052915', 'hire_date' => '2020-02-03', 'base_salary' => 160.00, 'contract_type' => 'Vigilante', 'payment_method' => 'bank_transfer', 'email' => 'vicente.hernandez@uefrayluisamigosf.com', 'phone' => '584265543804', 'is_active' => true],
            ['id' => 69, 'user_id' => 69, 'first_name' => 'Yolly Suzaida', 'last_name' => 'Escalante Chacon', 'identification' => '10780073', 'hire_date' => '2022-01-06', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'yolly.escalante@uefrayluisamigosf.com', 'phone' => '584120508848', 'is_active' => true],
            ['id' => 70, 'user_id' => 70, 'first_name' => 'Pedro Rafael', 'last_name' => 'Salom Azoca', 'identification' => '7911236', 'hire_date' => '2022-08-22', 'base_salary' => 440.00, 'contract_type' => 'Supervisor Servicios Generales', 'payment_method' => 'bank_transfer', 'email' => 'pedro.salom@uefrayluisamigosf.com', 'phone' => '584125453681', 'is_active' => true],
            ['id' => 71, 'user_id' => 71, 'first_name' => 'Jose Francisco', 'last_name' => 'Lopez Arocha', 'identification' => '23574313', 'hire_date' => '2022-07-01', 'base_salary' => 160.00, 'contract_type' => 'Jardinero', 'payment_method' => 'bank_transfer', 'email' => 'jose.lopez@uefrayluisamigosf.com', 'phone' => '584245316730', 'is_active' => true],
            ['id' => 72, 'user_id' => 72, 'first_name' => 'Kenny', 'last_name' => 'Espinoza', 'identification' => '18054827', 'hire_date' => '2022-08-25', 'base_salary' => 160.00, 'contract_type' => 'Vigilante', 'payment_method' => 'bank_transfer', 'email' => 'kenny.espinoza@uefrayluisamigosf.com', 'phone' => '584125453681', 'is_active' => true],
            ['id' => 73, 'user_id' => 73, 'first_name' => 'Charlie', 'last_name' => 'Castillo', 'identification' => '19061115', 'hire_date' => '2023-01-01', 'base_salary' => 160.00, 'contract_type' => 'Jardinero', 'payment_method' => 'bank_transfer', 'email' => 'charlie.castillo@uefrayluisamigosf.com', 'phone' => '584245064572', 'is_active' => true],
            ['id' => 74, 'user_id' => 74, 'first_name' => 'Franklin', 'last_name' => 'Moreno', 'identification' => '23575329', 'hire_date' => '2023-01-01', 'base_salary' => 160.00, 'contract_type' => 'Servicios Generales', 'payment_method' => 'bank_transfer', 'email' => 'franklin.moreno@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 75, 'user_id' => 75, 'first_name' => 'Jose Miguel Quintero', 'last_name' => 'Quintero', 'identification' => '15284807', 'hire_date' => '2023-11-01', 'base_salary' => 160.00, 'contract_type' => 'Chofer/Aseador', 'payment_method' => 'bank_transfer', 'email' => 'jose.quintero@uefrayluisamigosf.com', 'phone' => '584125068420', 'is_active' => true],
            ['id' => 76, 'user_id' => 76, 'first_name' => 'Eli Samuel', 'last_name' => 'Alvarez Mendoza', 'identification' => '28253837', 'hire_date' => '2024-03-04', 'base_salary' => 160.00, 'contract_type' => 'Jardinero', 'payment_method' => 'bank_transfer', 'email' => 'eli.alvarez@uefrayluisamigosf.com', 'phone' => '584265543804', 'is_active' => true],
            ['id' => 77, 'user_id' => 77, 'first_name' => 'Dennys Jesus', 'last_name' => 'Quiroga Salazar', 'identification' => '20467726', 'hire_date' => '2024-05-31', 'base_salary' => 160.00, 'contract_type' => 'Vigilante', 'payment_method' => 'bank_transfer', 'email' => 'dennys.quiroga@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 78, 'user_id' => 78, 'first_name' => 'Roenis Jose', 'last_name' => 'Rodriguez Rodriguez', 'identification' => '15107312', 'hire_date' => '2024-06-07', 'base_salary' => 160.00, 'contract_type' => 'Vigilante', 'payment_method' => 'bank_transfer', 'email' => 'roenis.rodriguez@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 79, 'user_id' => 79, 'first_name' => 'Greisy', 'last_name' => 'Paez', 'identification' => '17698128', 'hire_date' => '2024-10-14', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'greisy.paez@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 80, 'user_id' => 80, 'first_name' => 'Naya Cristina', 'last_name' => 'Colmenares Osorio', 'identification' => '21302128', 'hire_date' => '2025-01-07', 'base_salary' => 160.00, 'contract_type' => 'Aseadora', 'payment_method' => 'bank_transfer', 'email' => 'naya.colmenares@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 81, 'user_id' => 81, 'first_name' => 'Maria Eneda', 'last_name' => 'Barrios Ochoa', 'identification' => '18303046', 'hire_date' => '2016-05-02', 'base_salary' => 270.00, 'contract_type' => 'Supervisor Mantenimiento', 'payment_method' => 'bank_transfer', 'email' => 'maria.barrios@uefrayluisamigosf.com', 'phone' => '584245064572', 'is_active' => true],

            // Personal Directivo, Administrativo y Religioso - worker_id 82+
            ['id' => 82, 'user_id' => 82, 'first_name' => 'Ezequiel Jose', 'last_name' => 'Sierra Rodriguez', 'identification' => '5625888', 'hire_date' => '2017-08-01', 'base_salary' => 704.30, 'contract_type' => 'Director General', 'payment_method' => 'bank_transfer', 'email' => 'ezequiel.sierra@uefrayluisamigosf.com', 'phone' => '584122912430', 'is_active' => true],

            // Personal Administrativo - worker_id 83+
            ['id' => 83, 'user_id' => 83, 'first_name' => 'Anaines Elizabeth', 'last_name' => 'Suarez Clisanches', 'identification' => '18547787', 'hire_date' => '2019-01-10', 'base_salary' => 200.00, 'contract_type' => 'Asistente Control Estudiantil', 'payment_method' => 'bank_transfer', 'email' => 'anaines.suarez@uefrayluisamigosf.com', 'phone' => '584120508848', 'is_active' => true],
            ['id' => 84, 'user_id' => 84, 'first_name' => 'Yanira', 'last_name' => 'Ledezma Valles', 'identification' => '10859570', 'hire_date' => '2020-10-13', 'base_salary' => 600.00, 'contract_type' => 'Administradora Adjunta', 'payment_method' => 'bank_transfer', 'email' => 'yanira.ledezma@uefrayluisamigosf.com', 'phone' => '584125108520', 'is_active' => true],
            ['id' => 85, 'user_id' => 85, 'first_name' => 'Marielys De Jesus', 'last_name' => 'Bastidas Montilla', 'identification' => '19455017', 'hire_date' => '2021-10-15', 'base_salary' => 200.00, 'contract_type' => 'Asistente Administrativo', 'payment_method' => 'bank_transfer', 'email' => 'marielys.bastidas@uefrayluisamigosf.com', 'phone' => '584166537183', 'is_active' => true],
            ['id' => 86, 'user_id' => 86, 'first_name' => 'Lisbeth', 'last_name' => 'Verastegui', 'identification' => '7591923', 'hire_date' => '2023-01-09', 'base_salary' => 440.00, 'contract_type' => 'Asistente Admin. Dir. Acad.', 'payment_method' => 'bank_transfer', 'email' => 'lisbeth.verastegui@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 87, 'user_id' => 87, 'first_name' => 'Jesus', 'last_name' => 'Rodriguez', 'identification' => '18054188', 'hire_date' => '2023-09-11', 'base_salary' => 440.00, 'contract_type' => 'Tecnico Informatica', 'payment_method' => 'bank_transfer', 'email' => 'jesus.rodriguez@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],

            // Personal sin cuenta nómina - worker_id 88+
            ['id' => 88, 'user_id' => 88, 'first_name' => 'Ricardo Jose', 'last_name' => 'Goitia Gonzalez', 'identification' => '14798635', 'hire_date' => '2025-01-30', 'base_salary' => 160.00, 'contract_type' => 'Vigilante', 'payment_method' => 'bank_transfer', 'email' => 'ricardo.goitia@uefrayluisamigosf.com', 'phone' => '584160487540', 'is_active' => true],
            ['id' => 89, 'user_id' => 89, 'first_name' => 'Mabelys Andreina', 'last_name' => 'Montero Tovar', 'identification' => '15107995', 'hire_date' => '2025-02-03', 'base_salary' => 200.00, 'contract_type' => 'Asistente Administrativo', 'payment_method' => 'bank_transfer', 'email' => 'mabelys.montero@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 90, 'user_id' => 90, 'first_name' => 'Jose De La Cruz', 'last_name' => 'Rivero Escudero', 'identification' => '19454303', 'hire_date' => '2019-05-20', 'base_salary' => 540.00, 'contract_type' => 'Coord. Pastoral', 'payment_method' => 'bank_transfer', 'email' => 'jose.rivero@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 91, 'user_id' => 91, 'first_name' => 'Felicita Esmelanda', 'last_name' => 'Mendoza Martinez', 'identification' => '8515284', 'hire_date' => '2025-02-10', 'base_salary' => 440.00, 'contract_type' => 'Docente de Aula', 'payment_method' => 'bank_transfer', 'email' => 'felicita.mendoza@uefrayluisamigosf.com', 'phone' => '584143545645', 'is_active' => true],
            ['id' => 92, 'user_id' => 92, 'first_name' => 'Carlos Educardo', 'last_name' => 'Medina Rea', 'identification' => '16951922', 'hire_date' => '2025-03-05', 'base_salary' => 297.00, 'contract_type' => 'Docente por Hora', 'payment_method' => 'bank_transfer', 'email' => 'carlos.medina@uefrayluisamigosf.com', 'phone' => '584000000000', 'is_active' => true],
            ['id' => 93, 'user_id' => 93, 'first_name' => 'Dolimar', 'last_name' => 'Brito Dominguez', 'identification' => '12077583', 'hire_date' => '2025-02-10', 'base_salary' => 209.00, 'contract_type' => 'Docente por Hora Innov. T', 'payment_method' => 'bank_transfer', 'email' => 'dolimar.brito@uefrayluisamigosf.com', 'phone' => '584123457000', 'is_active' => true],
        ];

        foreach ($workers as $worker) {
            DB::table('workers')->updateOrInsert(
                ['id' => $worker['id']],
                [
                    'user_id' => $worker['user_id'],
                    'first_name' => $worker['first_name'],
                    'last_name' => $worker['last_name'],
                    'identification' => $worker['identification'],
                    'hire_date' => $worker['hire_date'],
                    'base_salary' => $worker['base_salary'],
                    'contract_type' => $worker['contract_type'],
                    'payment_method' => $worker['payment_method'],
                    'email' => $worker['email'],
                    'phone' => $worker['phone'],
                    'is_active' => $worker['is_active'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}